versions:
  "0.18.8.rc1-20240905-git-vili":
    folder: all
  "0.18.8.rc1-git-6f85c88-odr":
    folder: all
  "0.18.8.rc1-odr-git-3dcf842":
    folder: all
  "0.18.8.rc1-odr-git-e6c9ee6":
    folder: all
